### ISSUE TITLE
Simple-JNDI alongside Tomcat 8

### ISSUE THREAD

**Issue by jansohn** [h-thurow/Simple-JNDI#3]
I'm trying to use Simple-JNDI with Tomcat 8 so I can use a different connection pool with Eclipselink (JPA) without having to configure the JNDI resource in Tomcat itself.

This answer on stackoverflow indicates that it was working with Tomcat 6 at least: https://stackoverflow.com/a/13936449/3375325

I'd like to use HikariCP instead of Eclipselink's internal connection pooling, so what I do is create a `HikariDataSource` and try to bind it to a name, e.g. `jdbc/OracleHikariDatasource` in my WebListener's `contextInitialized` method. Unfortunately it already fails when calling `new InitialContext()` with the following `RuntimeException`:

    java.lang.RuntimeException: Illegal node/branch clash. At branch value 'Property' an Object was found: [TEST, /logfiles/TEST/webapp]
        at org.osjava.sj.loader.JndiLoader.createSubContexts(JndiLoader.java:310) ~[simple-jndi-0.14.0.jar:?]
        at org.osjava.sj.loader.JndiLoader.jndiPut(JndiLoader.java:290) ~[simple-jndi-0.14.0.jar:?]
        at org.osjava.sj.loader.JndiLoader.load(JndiLoader.java:223) ~[simple-jndi-0.14.0.jar:?]
        at org.osjava.sj.loader.JndiLoader.loadDirectory(JndiLoader.java:125) ~[simple-jndi-0.14.0.jar:?]
        at org.osjava.sj.loader.JndiLoader.loadDirectory(JndiLoader.java:82) ~[simple-jndi-0.14.0.jar:?]
        at org.osjava.sj.SimpleJndi.loadRoot(SimpleJndi.java:78) ~[simple-jndi-0.14.0.jar:?]
        at org.osjava.sj.SimpleContextFactory.getInitialContext(SimpleContextFactory.java:72) ~[simple-jndi-0.14.0.jar:?]
        at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:684) ~[?:1.8.0_131]
        at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:313) ~[?:1.8.0_131]
        at javax.naming.InitialContext.init(InitialContext.java:244) ~[?:1.8.0_131]
        at javax.naming.InitialContext.<init>(InitialContext.java:192) ~[?:1.8.0_131]
        [...]

The mentioned directory is where log4j2 places the log files of my web application.

**jndi.properties** (placed under `src/main/resources`)

    java.naming.factory.initial=org.osjava.sj.SimpleContextFactory
    org.osjava.sj.root=conf/

**WebListener**
```java
    @Override
    public synchronized void contextInitialized(ServletContextEvent event) {
        System.setProperty(Context.INITIAL_CONTEXT_FACTORY, "org.osjava.sj.SimpleContextFactory");

        try {
            Configuration config = new Configuration();
            Context ctx = new InitialContext();
            ctx.bind("jdbc/OracleHikariDatasource", config.getDataSource());
        } catch (NamingException | SQLException | RuntimeException ex) {
            log.error(ex.getMessage(), ex);
        }
    }
```

Is this supposed to work? Am I doing something wrong?

**Comment by h-thurow** [comment]
With "org.osjava.sj.root=conf/" Simple-JNDI scans all files and directories in "conf" and creates contexts according their names and keys, they contain. So it is easy to run into name collisions. In your case it looks like there is already an object bound to the name "Property", when trying to bound another one to the same name.

I would suggest to change "conf" to a directory exlusively owned by Simple-JNDI and putting your DataSource definition file there. Or you can load the file directly. See https://github.com/h-thurow/Simple-JNDI/wiki/Load-property-files-with-any-extension-from-any-location-(New-in-0.13.0) .

**Comment by jansohn** [comment]
That was it! Other files in the `conf` directory got in the way. Thank you very much!
